// Get all persons
GET http://localhost:3001/persons

###

// Get person by Id
GET http://localhost:3001/persons/630bf5491c43e127af5bef99

###

// Delete person
DELETE http://localhost:3001/persons/630c0b9c1340e7ac8a7756c9

###

// Post person
POST http://localhost:3001/persons
content-type: application/json

{
    "name": "Ian Rosales",
    "number": "11-12345678",
    "userId": "6314b2d6fa96e6220e399ed5"
}

###

// Put person
PUT http://localhost:3001/persons/630bf5491c43e127af5bef51123123
content-type: application/json

{
    "name": "Ian",
    "number": "11-23913641"
}
